import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, ArrowDown, Check, CircleDot, Layers3, Factory, Truck } from 'lucide-react';
import products from '@/lib/products.json';
import { ProductCard } from '@/components/product-card';
import { ContactCTA } from '@/components/site-footer';
import { strengths, customSolutions, range } from '@/lib/company';
export const metadata: Metadata = { alternates: { canonical: '/' } };
export default function Home() { return <>
  <section className="hero"><div className="hero-photo"><Image src="/images/hero-precast-factory-2026.webp" alt="Professional RCC pipe manufacturing yard with safe lifting operations" fill priority sizes="100vw" /><div className="hero-photo-shade" /></div><div className="container hero-content"><span className="eyebrow hero-eyebrow"><span className="status-dot" /> TUMAKURU, KARNATAKA · SINCE 2005</span><h1>Strong concrete.<br /><em>Reliable supply.</em></h1><p>RCC pipes and precast products for roads, drainage, irrigation and building projects.</p><div className="hero-actions"><Link href="/products/" className="button">View our products <ArrowUpRight size={20} /></Link><Link href="/contact/" className="hero-secondary">Send an enquiry <ArrowUpRight size={18} /></Link></div><div className="hero-bottom"><a href="#introduction"><ArrowDown size={16} /> About our company</a><span>RCC PIPES & PRECAST PRODUCTS</span></div></div><div className="hero-caption"><span>01 / MANUFACTURING</span><span>Tumakuru, India</span></div></section>
  <section className="proof-strip"><div className="container proof-grid"><div><span className="proof-number">2005<span>↗</span></span><p>A legacy of concrete expertise</p></div><div><CircleDot /><p>Premium quality.<br /><strong>Seamless finish.</strong></p></div><div><Factory /><p>Modern manufacturing.<br /><strong>Customized solutions.</strong></p></div><div><Truck /><p>Timely delivery.<br /><strong>Transparent dealings.</strong></p></div></div></section>
  <section id="introduction" className="section introduction"><div className="container intro-grid"><div><span className="eyebrow">MADE FOR REAL PROJECTS</span><h2>Concrete products.<br />Made since <span className="accent">2005.</span></h2><p>We manufacture RCC Hume pipes, manholes, kerb stones, drain covers and other precast products in Tumakuru.</p><p>We focus on consistent quality, clear communication and reliable delivery.</p><Link href="/about/" className="text-link">About our company <ArrowUpRight size={19} /></Link></div><div className="intro-image"><Image src="/images/about-quality-inspection-2026.webp" alt="Quality inspector checking a newly made RCC concrete pipe" width={1536} height={1024} /><div className="image-note"><Layers3 size={25} /><span>Checked for quality.<br /><strong>Ready for your project.</strong></span></div></div></div></section>
  <section className="section products-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">OUR MAIN PRODUCTS</span><h2>Built for strength.<br />Made to fit.</h2></div><div><p>Choose from concrete pipes, road products, drainage products and custom precast items.</p><Link href="/products/" className="text-link">View all products <ArrowUpRight size={19} /></Link></div></div><div className="product-grid featured-grid">{[products[0], products[9], products[11]].map((p, i) => <ProductCard product={p} index={i} key={p.slug} />)}</div><div className="product-range"><span>RCC Hume pipes</span><span>Precast manholes</span><span>Kerb stones</span><span>Paver blocks</span><span>Custom precast</span></div></div></section>
  <section className="section solutions-section"><div className="container solutions-grid"><div className="solutions-visual"><Image src="/images/custom-precast-site-2026.webp" alt="Precast drainage products at a professionally managed project site" width={1536} height={1024} /><span className="visual-label">MADE FOR YOUR SITE.</span></div><div><span className="eyebrow">CUSTOM PRECAST PRODUCTS</span><h2>Your requirement.<br />Our solution.</h2><p>{customSolutions}</p><p>{range}</p><Link className="text-link" href="/contact/">Ask about a custom product <ArrowUpRight size={19} /></Link></div></div></section>
  <section className="section why-section"><div className="container why-grid"><div><span className="eyebrow">WHY TUMKUR CONCRETE</span><h2>Good products.<br />Better partnerships.</h2><p>By providing quality products and having experienced knowledge of the market, we have been able to attain a huge client base.</p><blockquote>“We aim to be the leading manufacturer and supplier of precast concrete products and services, dedicated to delivering exceptional quality and value to our clients.”<cite>Shaheed Aleem <span>· Tumkur Concrete Spun Pipes</span></cite></blockquote></div><div className="strength-list">{strengths.map((s, i) => <div key={s}><span>{String(i + 1).padStart(2, '0')}</span><h3>{s}</h3><Check size={20} /></div>)}</div></div></section>
  <ContactCTA />
  </>; }
